### ISSUE TITLE
Don't find out source of function

### ISSUE THREAD

**Issue by NguyenThanhAI** [baofff/Extended-Analytic-DPM#2]
Thanks for your excellent work. I have a question. When I run train DPM on CelebA dataset, I encountered an error
```
download_file_from_google_drive(file_id, os.path.join(self.root, self.base_folder), filename, md5)
NameError: name 'download_file_from_google_drive' is not defined
```

I searched but I don't find out source of this function. Can you help me to fix this? Thank you very much.

**Comment by baofff** [comment]
We manually download the dataset. So we didn't use this line of code.

You can manually download the dataset (`img_align_celeba.zip` from link `https://drive.google.com/drive/folders/0B7EVK8r0v71pTUZsaXdaSnZBZzg?resourcekey=0-rJlzl934LzC-Xp28GeIBzQ`), and extract  the file to directory `assets/datasets/celeba/celeba/img_align_celeba`.

**Comment by NguyenThanhAI** [comment]
Thank you very much.
