### ISSUE TITLE
fid_stat not found

### ISSUE THREAD

**Issue by NguyenThanhAI** [baofff/Extended-Analytic-DPM#3]
Hi, After training the NPR and SN model, I run evaluation but I encounter error
```
assert os.path.exists(self.dataset.fid_stat)
AssertionError
```
I found:
```
@property
    def fid_stat(self):
        return 'workspace/fid_stats/fid_stats_cifar10_train_pytorch.npz'
```
But I can not find this file in workspace folder (created when I run training). How can I fix this error?

**Comment by shawnricecake** [comment]
download it through the given link in readme
